server.port=9009
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# minio.windows-amd64.RELEASE.2025-09-07T16-13-09Z.exe server C:\minio\data --console-address ":9001"